adapter: postgresql
encoding: unicode
host: ec2-54-247-92-185.eu-west-1.compute.amazonaws.com
pool: 5
username: zzjknnhhlyhebw
password: 34f5e08a51086cf5f5338b8b463ea9d2d005fc48914e69a7d1fabaaf06631ae0
database: dbsjs2hc6t9vip
