telegram:
  token: 368207201:AAEdqDMQAyOiWcaOG-kHCIB2GS_cPits-AI
  name: 'Erisu_bot'
debug_level: info
redis_url: 'redis://redistogo:530b31a6f775ed18866f4e9b77168e60@jack.redistogo.com:9117'
punctuation:
  end_sentense: '.!?'
  all: '.!?,;:'
anchors:
  - shizoid_bot
  - шизик
  - шиза
  - шизойд
  - наркоман
  - шизофазия
